[build]
  publish = "."
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/proxy-binance-demo/*"
  to = "/.netlify/functions/proxy?isDemo=true&endpoint=/:splat"
  status = 200

[[redirects]]
  from = "/proxy-binance-real/*"
  to = "/.netlify/functions/proxy?isDemo=false&endpoint=/:splat"
  status = 200

[[redirects]]
  from = "/proxy-binance/*"
  to = "/.netlify/functions/proxy?isDemo=false&endpoint=/:splat"
  status = 200

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-MBX-APIKEY, x-mbx-apikey, Authorization, *"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/bundle.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"